import { describe, expect, it } from "vitest";
import * as Troisi from "../index";

/** Runtime exports consumers import from @troisi/ui (types omitted). */
const RUNTIME_EXPORTS = [
	"Accordion",
	"Alert",
	"Avatar",
	"Badge",
	"Box",
	"Breadcrumb",
	"BreadcrumbItem",
	"Button",
	"Card",
	"Carousel",
	"Checkbox",
	"Chip",
	"Code",
	"CodeBlock",
	"ColorInput",
	"CommandPalette",
	"Container",
	"DateInput",
	"Divider",
	"Drawer",
	"EmptyState",
	"FieldError",
	"FieldHelper",
	"FileInput",
	"FocusTrap",
	"Form",
	"FormField",
	"Grid",
	"Icon",
	"Image",
	"Input",
	"Label",
	"Lightbox",
	"Link",
	"List",
	"ListItem",
	"Menu",
	"MenuItem",
	"Modal",
	"Navbar",
	"Pagination",
	"Popover",
	"Portal",
	"Progress",
	"Radio",
	"SearchInput",
	"Select",
	"Sidebar",
	"SidebarItem",
	"Skeleton",
	"Slider",
	"Spacer",
	"Spinner",
	"Stack",
	"Stat",
	"Stepper",
	"Switch",
	"Table",
	"TableSortHeader",
	"Tabs",
	"TabsList",
	"TabsPanel",
	"TabsTrigger",
	"Tag",
	"Textarea",
	"ThemeProvider",
	"Timeline",
	"TimelineItem",
	"ToastProvider",
	"Tooltip",
	"Typography",
	"Video",
	"VisuallyHidden",
	"applyTheme",
	"getSystemPrefersDark",
	"joinClasses",
	"readTheme",
	"resolveTheme",
	"TROISI_THEME_ATTR",
	"useClickOutside",
	"useFocusTrap",
	"useTheme",
	"useToast",
] as const;

describe("package exports", () => {
	it("exports every public runtime symbol", () => {
		const bag = Troisi as Record<string, unknown>;
		for (const name of RUNTIME_EXPORTS) {
			expect(bag[name], `missing export: ${name}`).toBeDefined();
		}
	});
});
